ifeq ($(FORTRAN90),yes)
al_MOD:=allocate_mod.$O
bk_MOD:=background_mod.$O
de_MOD:=detector_mod.$O
el_MOD:=element_mod.$O
g2_MOD:=geometry2d_mod.$O
gi_MOD:=geomint_mod.$O
cm_MOD:=macros_mod.$O
ma_MOD:=materials_mod.$O
mp_MOD:=mpi_mod.$O
ou_MOD:=output_mod.$O
pm_MOD:=pmi_mod.$O
pd_MOD:=pmidata_mod.$O
pf_MOD:=pmiformat_mod.$O
pr_MOD:=problem_mod.$O
ps_MOD:=problem_mod.$O
ra_MOD:=ratecalc_mod.$O
rc_MOD:=reaction_mod.$O
rd_MOD:=reactiondata_mod.$O
rf_MOD:=readfilenames_mod.$O
sc_MOD:=sector_mod.$O
so_MOD:=sources_mod.$O
sp_MOD:=species_mod.$O
sa_MOD:=stat_mod.$O
tl_MOD:=tally_mod.$O
xs_MOD:=xsection_mod.$O
zn_MOD:=zone_mod.$O
allocate_mods:= $(al_MOD)
allocate.o: $(allocate_mods)
aux2dsetup_mods:= $(de_MOD) $(gi_MOD) $(zn_MOD)
aux2dsetup.o: $(aux2dsetup_mods)
boxgen_mods:= $(bk_MOD) $(de_MOD) $(ma_MOD) $(sc_MOD) $(so_MOD) $(sp_MOD) $(zn_MOD)
boxgen.o: $(boxgen_mods)
collide_mods:= $(bk_MOD) $(gi_MOD) $(pr_MOD) $(rc_MOD) $(rd_MOD) $(sp_MOD) $(zn_MOD)
collide.o: $(collide_mods)
composite_mods:= $(gi_MOD) $(zn_MOD)
composite.o: $(composite_mods)
conversions_mods:= $(bk_MOD) $(gi_MOD) $(pr_MOD) $(sp_MOD) $(tl_MOD) $(zn_MOD)
conversions.o: $(conversions_mods)
cramdadd_mods:= $(bk_MOD) $(pr_MOD) $(rc_MOD) $(rd_MOD) $(rf_MOD) $(sp_MOD) $(zn_MOD)
cramdadd.o: $(cramdadd_mods)
dataexam_mods:= $(pr_MOD) $(rc_MOD) $(xs_MOD)
dataexam.o: $(dataexam_mods)
datamatch_mods:= $(xs_MOD)
datamatch.o: $(datamatch_mods)
dediagsetup_mods:= $(de_MOD) $(gi_MOD) $(pr_MOD) $(sc_MOD) $(zn_MOD)
dediagsetup.o: $(dediagsetup_mods)
definegeometry2d_mods:= $(g2_MOD) $(ma_MOD) $(sc_MOD) $(zn_MOD)
definegeometry2d.o: $(definegeometry2d_mods)
degasinit_mods:= $(mp_MOD) $(pr_MOD) $(tl_MOD)
degasinit.o: $(degasinit_mods)
elementread_mods:= $(bk_MOD) $(el_MOD) $(mp_MOD) $(rc_MOD) $(rf_MOD) $(so_MOD) $(sp_MOD) $(zn_MOD)
elementread.o: $(elementread_mods)
elementsetup_mods:= $(el_MOD) $(rf_MOD)
elementsetup.o: $(elementsetup_mods)
flight_mods:= $(bk_MOD) $(pm_MOD) $(pr_MOD) $(rc_MOD) $(sa_MOD) $(sc_MOD) $(so_MOD) $(sp_MOD) $(tl_MOD) $(zn_MOD)
flight.o: $(flight_mods)
flighttest_mods:= $(de_MOD) $(mp_MOD) $(ou_MOD) $(pr_MOD) $(rf_MOD) $(sa_MOD) $(so_MOD) $(sp_MOD) $(tl_MOD) $(zn_MOD)
flighttest.o: $(flighttest_mods)
geometry_mods:= $(de_MOD) $(gi_MOD) $(mp_MOD) $(rf_MOD) $(sc_MOD) $(zn_MOD)
geometry.o: $(geometry_mods)
geomfront_mods:= $(gi_MOD) $(sc_MOD)
geomfront.o: $(geomfront_mods)
geomsetup_mods:= $(al_MOD) $(de_MOD) $(gi_MOD) $(rf_MOD) $(sc_MOD) $(zn_MOD)
geomsetup.o: $(geomsetup_mods)
geomtest_mods:= $(bk_MOD) $(zn_MOD)
geomtest.o: $(geomtest_mods)
geomtesta_mods:= $(bk_MOD) $(de_MOD) $(ou_MOD) $(pr_MOD) $(so_MOD) $(sp_MOD) $(tl_MOD) $(zn_MOD)
geomtesta.o: $(geomtesta_mods)
matcheir_mods:= $(ou_MOD) $(pr_MOD) $(so_MOD) $(sp_MOD) $(tl_MOD) $(zn_MOD)
matcheir.o: $(matcheir_mods)
matchout_mods:= $(ou_MOD) $(pr_MOD) $(rf_MOD) $(so_MOD) $(tl_MOD)
matchout.o: $(matchout_mods)
materialsetup_mods:= $(ma_MOD) $(rf_MOD)
materialsetup.o: $(materialsetup_mods)
outputbrowser_mods:= $(de_MOD) $(ou_MOD) $(pm_MOD) $(pr_MOD) $(rc_MOD) $(sc_MOD) $(so_MOD) $(sp_MOD) $(tl_MOD) $(zn_MOD)
outputbrowser.o: $(outputbrowser_mods)
plate_mods:= $(pd_MOD) $(pf_MOD) $(pm_MOD) $(pr_MOD) $(sp_MOD)
plate.o: $(plate_mods)
plotgeom_mods:= $(bk_MOD) $(gi_MOD) $(zn_MOD)
plotgeom.o: $(plotgeom_mods)
pmimatread_mods:= $(ma_MOD) $(mp_MOD) $(ou_MOD) $(pd_MOD) $(pm_MOD) $(pr_MOD) $(rd_MOD) $(rf_MOD) $(so_MOD) $(sp_MOD) $(tl_MOD)
pmimatread.o: $(pmimatread_mods)
pmisetup_mods:= $(ma_MOD) $(pm_MOD) $(rf_MOD) $(sp_MOD)
pmisetup.o: $(pmisetup_mods)
pmitest_mods:= $(ma_MOD) $(pd_MOD) $(pm_MOD) $(pr_MOD) $(rc_MOD) $(sp_MOD)
pmitest.o: $(pmitest_mods)
pmiwrite_mods:= $(el_MOD) $(pf_MOD)
pmiwrite.o: $(pmiwrite_mods)
problemsetup_mods:= $(el_MOD) $(ma_MOD) $(pm_MOD) $(pr_MOD) $(ps_MOD) $(rc_MOD) $(rf_MOD) $(sp_MOD)
problemsetup.o: $(problemsetup_mods)
pvmmaster_mods:= $(zn_MOD)
pvmmaster.o: $(pvmmaster_mods)
pvmslave_mods:= $(zn_MOD)
pvmslave.o: $(pvmslave_mods)
ratecalc_mods:= $(ra_MOD) $(rf_MOD) $(xs_MOD)
ratecalc.o: $(ratecalc_mods)
reaction_mods:= $(bk_MOD) $(gi_MOD) $(pr_MOD) $(rc_MOD) $(rd_MOD) $(sp_MOD) $(xs_MOD) $(zn_MOD)
reaction.o: $(reaction_mods)
reactionsetup_mods:= $(rc_MOD) $(rf_MOD) $(sp_MOD)
reactionsetup.o: $(reactionsetup_mods)
reactiontest_mods:= $(el_MOD) $(pr_MOD) $(rc_MOD) $(rd_MOD) $(sp_MOD)
reactiontest.o: $(reactiontest_mods)
reactionwrite_mods:= $(xs_MOD)
reactionwrite.o: $(reactionwrite_mods)
readbackground_mods:= $(bk_MOD) $(el_MOD) $(gi_MOD) $(pr_MOD) $(rc_MOD) $(sc_MOD) $(so_MOD) $(sp_MOD) $(zn_MOD)
readbackground.o: $(readbackground_mods)
readfilenames_mods:= $(rf_MOD)
readfilenames.o: $(readfilenames_mods)
readgeometry_mods:= $(de_MOD) $(gi_MOD) $(ma_MOD) $(sc_MOD) $(zn_MOD)
readgeometry.o: $(readgeometry_mods)
score_mods:= $(bk_MOD) $(de_MOD) $(gi_MOD) $(ou_MOD) $(pr_MOD) $(rc_MOD) $(rd_MOD) $(sa_MOD) $(sc_MOD) $(so_MOD) $(sp_MOD) $(tl_MOD) $(zn_MOD)
score.o: $(score_mods)
sources_mods:= $(bk_MOD) $(el_MOD) $(gi_MOD) $(pr_MOD) $(sc_MOD) $(so_MOD) $(sp_MOD) $(zn_MOD)
sources.o: $(sources_mods)
sourcetest_mods:= $(sc_MOD) $(so_MOD) $(sp_MOD) $(zn_MOD)
sourcetest.o: $(sourcetest_mods)
speciesetup_mods:= $(el_MOD) $(rf_MOD) $(sp_MOD)
speciesetup.o: $(speciesetup_mods)
stat_mods:= $(ou_MOD) $(pr_MOD) $(sa_MOD) $(tl_MOD)
stat.o: $(stat_mods)
sysdep_mods:= $(mem_MOD)
sysdep.o: $(sysdep_mods)
tallysetup_mods:= $(de_MOD) $(gi_MOD) $(pr_MOD) $(rc_MOD) $(rf_MOD) $(sc_MOD) $(so_MOD) $(sp_MOD) $(tl_MOD) $(zn_MOD)
tallysetup.o: $(tallysetup_mods)
updatebackground_mods:= $(bk_MOD) $(pr_MOD) $(rf_MOD) $(so_MOD) $(zn_MOD)
updatebackground.o: $(updatebackground_mods)
writeback_mods:= $(bk_MOD) $(gi_MOD) $(pr_MOD) $(rf_MOD) $(sc_MOD) $(so_MOD) $(sp_MOD) $(zn_MOD)
writeback.o: $(writeback_mods)
endif
ifeq ($(STANDALONE),yes)
allocate.f: allocate.hweb array.hweb constants.hweb macros.hweb sysdep.hweb vector.hweb
aux2dsetup.f: array.hweb constants.hweb detector.hweb geomint.hweb macros.hweb sysdep.hweb vector.hweb zone.hweb
boxgen.f: array.hweb background.hweb constants.hweb detector.hweb geomint.hweb location.hweb macros.hweb materials.hweb sector.hweb sources.hweb species.hweb string.hweb sysdep.hweb vector.hweb zone.hweb
classes.f: array.hweb background.hweb classes.hweb detector.hweb element.hweb flight.hweb location.hweb materials.hweb netcdf.hweb output.hweb particle.hweb pmi.hweb pmidata.hweb pmiformat.hweb problem.hweb random.hweb ratecalc.hweb reaction.hweb reactiondata.hweb readfilenames.hweb sector.hweb sources.hweb species.hweb stat.hweb string.hweb tally.hweb vector.hweb xsection.hweb zone.hweb
collide.f: array.hweb background.hweb constants.hweb geomint.hweb location.hweb macros.hweb materials.hweb output.hweb particle.hweb problem.hweb random.hweb reaction.hweb reactiondata.hweb sector.hweb sources.hweb species.hweb string.hweb sysdep.hweb tally.hweb vector.hweb xsection.hweb zone.hweb
composite.f: array.hweb constants.hweb geomint.hweb location.hweb macros.hweb sysdep.hweb vector.hweb zone.hweb
conversions.f: array.hweb background.hweb constants.hweb geomint.hweb location.hweb macros.hweb materials.hweb output.hweb particle.hweb problem.hweb reaction.hweb sector.hweb sources.hweb species.hweb string.hweb sysdep.hweb tally.hweb vector.hweb zone.hweb
cramdadd.f: array.hweb background.hweb constants.hweb macros.hweb materials.hweb problem.hweb reaction.hweb reactiondata.hweb readfilenames.hweb species.hweb string.hweb sysdep.hweb vector.hweb xsection.hweb zone.hweb
cramdproblem.f: array.hweb constants.hweb macros.hweb sysdep.hweb vector.hweb
cramdtesta.f: array.hweb constants.hweb macros.hweb string.hweb sysdep.hweb vector.hweb
dataexam.f: array.hweb background.hweb constants.hweb location.hweb macros.hweb materials.hweb netcdf.hweb particle.hweb problem.hweb reaction.hweb reactiondata.hweb sources.hweb species.hweb string.hweb sysdep.hweb vector.hweb xsection.hweb zone.hweb
datamatch.f: array.hweb constants.hweb macros.hweb netcdf.hweb reaction.hweb string.hweb sysdep.hweb vector.hweb xsection.hweb
datasetup.f: array.hweb constants.hweb macros.hweb sysdep.hweb vector.hweb
dediagsetup.f: array.hweb constants.hweb detector.hweb geomint.hweb location.hweb macros.hweb materials.hweb problem.hweb reaction.hweb sector.hweb species.hweb sysdep.hweb vector.hweb zone.hweb
definegeometry2d.f: array.hweb constants.hweb geometry2d.hweb geomint.hweb location.hweb macros.hweb materials.hweb netcdf.hweb sector.hweb string.hweb sysdep.hweb vector.hweb zone.hweb
degasinit.f: array.hweb constants.hweb macros.hweb materials.hweb mpi.hweb netcdf.hweb output.hweb pmi.hweb pmidata.hweb pmiformat.hweb problem.hweb reaction.hweb reactiondata.hweb readfilenames.hweb sector.hweb sources.hweb species.hweb string.hweb sysdep.hweb tally.hweb vector.hweb xsection.hweb zone.hweb
elementread.f: array.hweb background.hweb constants.hweb element.hweb macros.hweb mpi.hweb netcdf.hweb reaction.hweb readfilenames.hweb sources.hweb species.hweb sysdep.hweb vector.hweb zone.hweb
elementsetup.f: array.hweb constants.hweb element.hweb macros.hweb netcdf.hweb readfilenames.hweb string.hweb sysdep.hweb vector.hweb
flight.f: array.hweb background.hweb constants.hweb flight.hweb location.hweb macros.hweb materials.hweb output.hweb particle.hweb pmi.hweb pmidata.hweb pmiformat.hweb problem.hweb random.hweb reaction.hweb sector.hweb sources.hweb species.hweb stat.hweb string.hweb sysdep.hweb tally.hweb vector.hweb zone.hweb
flighttest.f: array.hweb constants.hweb detector.hweb macros.hweb materials.hweb mpi.hweb netcdf.hweb output.hweb problem.hweb random.hweb reaction.hweb readfilenames.hweb sector.hweb sources.hweb species.hweb stat.hweb string.hweb sysdep.hweb tally.hweb vector.hweb zone.hweb
geometry.f: array.hweb constants.hweb detector.hweb geomint.hweb location.hweb macros.hweb materials.hweb mpi.hweb netcdf.hweb particle.hweb problem.hweb reaction.hweb readfilenames.hweb sector.hweb sources.hweb species.hweb sysdep.hweb vector.hweb zone.hweb
geomfaces.f: array.hweb constants.hweb geomint.hweb location.hweb macros.hweb sysdep.hweb vector.hweb
geomfront.f: array.hweb constants.hweb geomint.hweb location.hweb macros.hweb materials.hweb particle.hweb problem.hweb reaction.hweb sector.hweb sources.hweb species.hweb sysdep.hweb vector.hweb
geomsetup.f: allocate.hweb array.hweb constants.hweb detector.hweb geomint.hweb macros.hweb netcdf.hweb readfilenames.hweb sector.hweb sysdep.hweb vector.hweb zone.hweb
geomtest.f: array.hweb background.hweb constants.hweb geomint.hweb location.hweb macros.hweb materials.hweb particle.hweb problem.hweb reaction.hweb sources.hweb species.hweb sysdep.hweb vector.hweb zone.hweb
geomtesta.f: array.hweb background.hweb constants.hweb detector.hweb geomint.hweb macros.hweb materials.hweb netcdf.hweb output.hweb problem.hweb reaction.hweb readfilenames.hweb sector.hweb sources.hweb species.hweb string.hweb sysdep.hweb tally.hweb vector.hweb zone.hweb
geomtestb.f: array.hweb constants.hweb geomint.hweb macros.hweb sysdep.hweb vector.hweb
geomutils.f: array.hweb constants.hweb geomint.hweb macros.hweb sysdep.hweb vector.hweb
interpolate.f: array.hweb constants.hweb macros.hweb sysdep.hweb vector.hweb
matcheir.f: array.hweb background.hweb constants.hweb macros.hweb materials.hweb netcdf.hweb output.hweb problem.hweb reaction.hweb readfilenames.hweb sector.hweb sources.hweb species.hweb string.hweb sysdep.hweb tally.hweb vector.hweb zone.hweb
matchout.f: array.hweb background.hweb constants.hweb macros.hweb materials.hweb netcdf.hweb output.hweb problem.hweb reaction.hweb readfilenames.hweb sector.hweb sources.hweb species.hweb string.hweb sysdep.hweb tally.hweb vector.hweb zone.hweb
materialsetup.f: array.hweb constants.hweb macros.hweb materials.hweb netcdf.hweb readfilenames.hweb string.hweb sysdep.hweb vector.hweb
outputbrowser.f: array.hweb constants.hweb detector.hweb macros.hweb materials.hweb output.hweb pmi.hweb problem.hweb reaction.hweb sector.hweb sources.hweb species.hweb string.hweb sysdep.hweb tally.hweb vector.hweb zone.hweb
plate.f: array.hweb constants.hweb location.hweb macros.hweb materials.hweb netcdf.hweb particle.hweb pmi.hweb pmidata.hweb pmiformat.hweb problem.hweb random.hweb reaction.hweb sources.hweb species.hweb string.hweb sysdep.hweb vector.hweb
plotgeom.f: array.hweb background.hweb constants.hweb geomint.hweb location.hweb macros.hweb materials.hweb problem.hweb reaction.hweb species.hweb sysdep.hweb vector.hweb zone.hweb
pmimatread.f: array.hweb constants.hweb macros.hweb materials.hweb mpi.hweb netcdf.hweb output.hweb pmi.hweb pmidata.hweb pmiformat.hweb problem.hweb reaction.hweb reactiondata.hweb readfilenames.hweb sector.hweb sources.hweb species.hweb string.hweb sysdep.hweb tally.hweb vector.hweb xsection.hweb zone.hweb
pmisetup.f: array.hweb constants.hweb macros.hweb materials.hweb netcdf.hweb pmi.hweb readfilenames.hweb species.hweb string.hweb sysdep.hweb vector.hweb
pmitest.f: array.hweb constants.hweb macros.hweb materials.hweb pmi.hweb pmidata.hweb pmiformat.hweb problem.hweb random.hweb reaction.hweb species.hweb string.hweb sysdep.hweb vector.hweb
pmiwrite.f: array.hweb constants.hweb element.hweb macros.hweb netcdf.hweb pmi.hweb pmiformat.hweb readfilenames.hweb string.hweb sysdep.hweb vector.hweb
problemsetup.f: array.hweb constants.hweb element.hweb macros.hweb materials.hweb netcdf.hweb pmi.hweb pmidata.hweb pmiformat.hweb problem.hweb reaction.hweb readfilenames.hweb species.hweb string.hweb sysdep.hweb vector.hweb
pvmmaster.f: array.hweb constants.hweb macros.hweb pvm.hweb random.hweb string.hweb sysdep.hweb vector.hweb zone.hweb
pvmslave.f: array.hweb constants.hweb macros.hweb pvm.hweb random.hweb string.hweb sysdep.hweb vector.hweb zone.hweb
random.f: array.hweb constants.hweb macros.hweb random.hweb sysdep.hweb vector.hweb
randomtest.f: array.hweb constants.hweb macros.hweb random.hweb sysdep.hweb vector.hweb
randother.f: array.hweb constants.hweb macros.hweb random.hweb sysdep.hweb vector.hweb
ratecalc.f: array.hweb constants.hweb macros.hweb netcdf.hweb ratecalc.hweb reaction.hweb readfilenames.hweb string.hweb sysdep.hweb vector.hweb xsection.hweb
reaction.f: array.hweb background.hweb constants.hweb geomint.hweb location.hweb macros.hweb materials.hweb netcdf.hweb particle.hweb problem.hweb random.hweb reaction.hweb reactiondata.hweb sources.hweb species.hweb string.hweb sysdep.hweb vector.hweb xsection.hweb zone.hweb
reactionsetup.f: array.hweb constants.hweb macros.hweb netcdf.hweb reaction.hweb readfilenames.hweb species.hweb string.hweb sysdep.hweb vector.hweb
reactiontest.f: array.hweb constants.hweb element.hweb macros.hweb materials.hweb output.hweb problem.hweb random.hweb reaction.hweb reactiondata.hweb sector.hweb sources.hweb species.hweb string.hweb sysdep.hweb tally.hweb vector.hweb xsection.hweb zone.hweb
reactionwrite.f: array.hweb constants.hweb macros.hweb netcdf.hweb reaction.hweb string.hweb sysdep.hweb vector.hweb xsection.hweb
readbackground.f: array.hweb background.hweb constants.hweb degas.hweb element.hweb geomint.hweb macros.hweb materials.hweb netcdf.hweb problem.hweb reaction.hweb readfilenames.hweb sector.hweb sources.hweb species.hweb string.hweb sysdep.hweb vector.hweb zone.hweb
readdegas.f: array.hweb constants.hweb degas.hweb geomint.hweb macros.hweb sysdep.hweb vector.hweb
readfilenames.f: array.hweb constants.hweb macros.hweb readfilenames.hweb string.hweb sysdep.hweb vector.hweb
readgeometry.f: array.hweb constants.hweb degas.hweb detector.hweb geomint.hweb macros.hweb materials.hweb readfilenames.hweb sector.hweb string.hweb sysdep.hweb vector.hweb zone.hweb
score.f: array.hweb background.hweb constants.hweb detector.hweb flight.hweb geomint.hweb location.hweb macros.hweb materials.hweb output.hweb particle.hweb pmi.hweb problem.hweb random.hweb reaction.hweb reactiondata.hweb sector.hweb sources.hweb species.hweb stat.hweb string.hweb sysdep.hweb tally.hweb vector.hweb xsection.hweb zone.hweb
sources.f: array.hweb background.hweb constants.hweb element.hweb flight.hweb geomint.hweb location.hweb macros.hweb materials.hweb output.hweb particle.hweb problem.hweb random.hweb reaction.hweb sector.hweb sources.hweb species.hweb string.hweb sysdep.hweb tally.hweb vector.hweb zone.hweb
sourcetest.f: array.hweb background.hweb constants.hweb flight.hweb location.hweb macros.hweb materials.hweb particle.hweb problem.hweb random.hweb reaction.hweb sector.hweb sources.hweb species.hweb string.hweb sysdep.hweb vector.hweb zone.hweb
speciesetup.f: array.hweb constants.hweb element.hweb macros.hweb netcdf.hweb readfilenames.hweb species.hweb string.hweb sysdep.hweb vector.hweb
stat.f: array.hweb constants.hweb macros.hweb materials.hweb output.hweb problem.hweb reaction.hweb sector.hweb sources.hweb species.hweb stat.hweb sysdep.hweb tally.hweb vector.hweb zone.hweb
string.f: array.hweb constants.hweb macros.hweb sysdep.hweb vector.hweb
sysdep.f: array.hweb constants.hweb macros.hweb sysdep.hweb vector.hweb
sysdeptest.f: array.hweb constants.hweb macros.hweb string.hweb sysdep.hweb vector.hweb
tallysetup.f: array.hweb constants.hweb detector.hweb element.hweb geomint.hweb location.hweb macros.hweb materials.hweb netcdf.hweb pmi.hweb pmidata.hweb pmiformat.hweb problem.hweb reaction.hweb readfilenames.hweb sector.hweb sources.hweb species.hweb string.hweb sysdep.hweb tally.hweb vector.hweb zone.hweb
template.f: array.hweb constants.hweb macros.hweb sysdep.hweb vector.hweb
teststring.f: array.hweb constants.hweb macros.hweb sysdep.hweb vector.hweb
updatebackground.f: array.hweb background.hweb constants.hweb macros.hweb materials.hweb netcdf.hweb problem.hweb reaction.hweb readfilenames.hweb sources.hweb species.hweb sysdep.hweb vector.hweb zone.hweb
voigt.f: array.hweb constants.hweb macros.hweb sysdep.hweb vector.hweb
voigtspec.f: array.hweb constants.hweb macros.hweb string.hweb sysdep.hweb vector.hweb
voigttest.f: array.hweb constants.hweb macros.hweb string.hweb sysdep.hweb vector.hweb
writeback.f: array.hweb background.hweb constants.hweb geomint.hweb location.hweb macros.hweb materials.hweb netcdf.hweb particle.hweb problem.hweb random.hweb reaction.hweb readfilenames.hweb sector.hweb sources.hweb species.hweb string.hweb sysdep.hweb vector.hweb zone.hweb
background_mod.f: zone.hweb
detector_mod.f: vector.hweb zone.hweb
macros_mod.f: array.hweb constants.hweb sysdep.hweb vector.hweb
output_mod.f: materials.hweb problem.hweb reaction.hweb sector.hweb sources.hweb species.hweb tally.hweb zone.hweb
pmidata_mod.f: materials.hweb pmi.hweb pmiformat.hweb problem.hweb reaction.hweb species.hweb
pmiformat_mod.f: pmi.hweb
problem_mod.f: materials.hweb reaction.hweb species.hweb
ratecalc_mod.f: reaction.hweb xsection.hweb
reactiondata_mod.f: materials.hweb problem.hweb reaction.hweb species.hweb xsection.hweb
stat_mod.f: materials.hweb output.hweb problem.hweb reaction.hweb sector.hweb sources.hweb species.hweb tally.hweb zone.hweb
tally_mod.f: materials.hweb problem.hweb reaction.hweb sector.hweb species.hweb zone.hweb
xsection_mod.f: reaction.hweb
endif
